apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: historian-reports-ingress
  namespace: historian-reports
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - reports.kagome.com.au
    secretName: kagome-reports-tls
  rules:
  - host: reports.kagome.com.au
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: historian-reports-service
            port:
              number: 3000
