apiVersion: v1
kind: Service
metadata:
  name: historian-reports-service
  namespace: historian-reports
  labels:
    app: historian-reports
spec:
  selector:
    app: historian-reports
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort
